package hibernate;
// Generated 27-ene-2014 9:07:27 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Carta generated by hbm2java
 */
public class Carta  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private BigDecimal precio;
     private Set detallepedidos = new HashSet(0);

    public Carta() {
    }

	
    public Carta(String nombre, BigDecimal precio) {
        this.nombre = nombre;
        this.precio = precio;
    }
    public Carta(String nombre, BigDecimal precio, Set detallepedidos) {
       this.nombre = nombre;
       this.precio = precio;
       this.detallepedidos = detallepedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Set getDetallepedidos() {
        return this.detallepedidos;
    }
    
    public void setDetallepedidos(Set detallepedidos) {
        this.detallepedidos = detallepedidos;
    }




}


