package hibernate;
// Generated 27-ene-2014 9:07:27 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Detallepedido generated by hbm2java
 */
public class Detallepedido  implements java.io.Serializable {


     private Integer id;
     private Carta carta;
     private Pedido pedido;
     private Integer cantidad;
     private BigDecimal precio;

    public Detallepedido() {
    }

	
    public Detallepedido(Carta carta, Pedido pedido, BigDecimal precio) {
        this.carta = carta;
        this.pedido = pedido;
        this.precio = precio;
    }
    public Detallepedido(Carta carta, Pedido pedido, Integer cantidad, BigDecimal precio) {
       this.carta = carta;
       this.pedido = pedido;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Carta getCarta() {
        return this.carta;
    }
    
    public void setCarta(Carta carta) {
        this.carta = carta;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


