package hibernate;
// Generated 27-ene-2014 9:07:27 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private Mesa mesa;
     private Date fechahora;
     private byte cerrado;
     private Set detallepedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Mesa mesa, Date fechahora, byte cerrado) {
        this.mesa = mesa;
        this.fechahora = fechahora;
        this.cerrado = cerrado;
    }
    public Pedido(Mesa mesa, Date fechahora, byte cerrado, Set detallepedidos) {
       this.mesa = mesa;
       this.fechahora = fechahora;
       this.cerrado = cerrado;
       this.detallepedidos = detallepedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public Date getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(Date fechahora) {
        this.fechahora = fechahora;
    }
    public byte getCerrado() {
        return this.cerrado;
    }
    
    public void setCerrado(byte cerrado) {
        this.cerrado = cerrado;
    }
    public Set getDetallepedidos() {
        return this.detallepedidos;
    }
    
    public void setDetallepedidos(Set detallepedidos) {
        this.detallepedidos = detallepedidos;
    }




}


